### PR TITLE
@SafeVarargs replacing @SuppressWanning

### PR DESCRIPTION
**Pull request by syluna**
@SafeVarargs maybe a better way to avoid warning safety check in subprojet unsing lemur

### CODE REVIEW

**Comment by pspeed42** [comment]
In both of these patches, I like the SafeVarArgs change but I don't think I like the 'final' change.  Subclasses should be able to intercept these methods, I think.

**Comment by syluna** [comment]
Maybe create new final method call non final, what do you think ?

**Comment by pspeed42** [comment]
Why does it need to be final?  If SafeVarArgs requires the method to be final then I think I like the old SuppressWarning solution better.  If SafeVarArgs doesn't require the final then just remove the final keyword and leave these methods with the same access that they had before.

**Comment by syluna** [comment]
SafeVarargs must have to final keyword :s
So I close this PR.

**Pull request closed without merging**
