### PR TITLE
Performance improvements during logging

### PR DESCRIPTION
**Pull request by Pesegato**

### CODE REVIEW

**Comment by pspeed42** [comment]
Well... in this case not really.  These are both only called once per application run first off... so any performance benefit is minor.  Since the idea is that INFO messages are usually logged then we don't get much benefit from the "not logged" optimization that the format version of the method provides.  So then it's a difference between a string append and a string format.  The append is always going to perform better in that case.  (And the compiler will catch typos.)

**Comment by pspeed42** [comment]
Thanks for the patch, though.  I'm glad others are looking at the code.

**Comment by Pesegato** [comment]
Hum. I thought that the string format was always preferable and therefore always use the {} syntax, if nothing else to remind the "better way" of logging... oh well.

**Comment by pspeed42** [comment]
The benefit of the {} syntax is that the logging system can avoid doing the
string format if the log message would be suppressed.  Else string + is
going to be faster.  The down side of the {} syntax is that if you get it
wrong then you don't know about it until that log message is output someday
and your application crashes.

In this case, the savings for {} would be so small as to not be measurable
(because these are logged once per app run) and considering the message is
almost always output then there would be no savings at all anyway.

For readability, cut+pastability, etc. I also prefer the string + string
form, personally.  So you will see it's rare that I use the {} form.

**Pull request closed without merging**
