### PR TITLE
Added the mousePressed event to DefaultMouseListener

### PR DESCRIPTION
**Pull request by Pesegato**

### CODE REVIEW

**Comment by Pesegato** [comment]
Reason behind this feature: I want to manage a Button that reacts on some way when is "pressed", and on another way when is "clicked"

**Comment by Pesegato** [comment]
Whoops! Doesn't even compile :dizzy_face:

**Comment by pspeed42** [comment]
But that's what mouseButtonEvent() is for.  Just override that method and
call the super method.

**Comment by pspeed42** [comment]
Also, even if I _were_ to add such a method (and I'm not strongly motivated
due to already stated reasons)... it would have to be protected because
it's not part of the public interface.

**Comment by Pesegato** [comment]
I've tried that first, but somehow I either got the pressed OR the click, not both. The most elegant solution is by adding it on the API.

Yes I see that is not part of the interface. But hey, "Default*Listeners" are for convenience, right? They are allowed to add new public methods...

**Comment by Pesegato** [comment]
Nevermind, it worked as you said. Feel free to discard my PR is you want.

**Pull request closed without merging**
