### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Pesegato**
Added the mousePressed event to DefaultMouseListener

### CODE REVIEW

**Comment by Pesegato** [comment]
The fixed version of #36

**Comment by Pesegato** [comment]
Nevermind, it worked as you said. Feel free to discard my PR is you want.

**Comment by Pesegato** [comment]
However... somehow your solution feels like an hack. mousePressed() has been part of AWT since 1.1 I think...

**Comment by pspeed42** [comment]
Yeah, but in that case it's part of the AWT MouseListener interface.  JME
uses a completely different event model... adding some protected method for
this isn't worth it as it provides no value.

**Pull request closed without merging**
