### PR TITLE
added tab button position to the tabbed panel, right-center-left.

### PR DESCRIPTION
**Pull request by RayanFar**
added tab button position to the tabbed panel, right-center-left.

### CODE REVIEW

**Comment by pspeed42** [comment]
Sorry I didn't see this before.  Gmail keeps changing its mind on where it will deliver notifications like this so sometimes I miss them.

I will try to look at it soon.

**Comment by pspeed42** [comment]
Two initial things:
1) why did you remove all of the default mappings setup from the focus manager.  As it is, I would have to reject this PR just on that unrelated change.
2) can you describe what *BoxLayout provides over SpringGridLayout?  Parts that concern me are that there are two nearly identical classes that only differ in their orientation.  Lemur tries to avoid this when possible especially considering that there is a third orientation that I don't think is supported by these.  (For example, SpringGridLayout can work with any pair of axes, X, Y or X, Z, or Y, X, etc.)

Knowing what BoxLayout does that SpringGridLayout doesn't will help me guide the solution.

**Comment by RayanFar** [comment]
1-changing focus in GUI elements by arrow keys in HUD made some problems because It interferes with game control mappings and there is no manual way to disable it, so I removed them.

2-Box layout has a clear way to position the elements in the left, center or right sides. I didn't remember why and I think  because of the fill mode of it when we use RTL languages tabs must sort like this: (tabPanel){left   center  [tab3] [tab2] [tab1]} not (tabPanel){left center [tab1] [tab2] [tab3]}

**Comment by pspeed42** [comment]
re: "1-changing focus in GUI elements by arrow keys in HUD made some problems because It interferes with game control mappings and there is no manual way to disable it, so I removed them."

a) yes, you can totally turn it off very easily.  b) it is unrelated to the tab panel changes and it's a shame that it would cause this PR to get rejected for an unrelated changes.

I will think more about (2).

**Comment by RayanFar** [comment]
if you agree with the second part {using v and box layout to position tabs} I will change the code and make a new PR.

would you please show me how to disable the key mapping of the lemur GUI in a jme project?

**Comment by pspeed42** [comment]
You should ask that question on the forum so that the answer will benefit everyone.  (I think it's already been answered on the forum, too, but I don't know if searching will find it.)

**Pull request closed without merging**
